<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="63" passed="36" failed="27" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-03T14:45:00 ICT" name="Default suite" finished-at="2023-08-03T14:45:18 ICT" duration-ms="18022">
    <groups>
    </groups>
    <test started-at="2023-08-03T14:45:00 ICT" name="Default test" finished-at="2023-08-03T14:45:18 ICT" duration-ms="18022">
      <class name="testing.QLNHTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testing.QLNHTest@69f080ad]" started-at="2023-08-03T14:45:00 ICT" name="setUp" finished-at="2023-08-03T14:45:02 ICT" duration-ms="1967" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testInsert()[pri:1, instance:testing.QLNHTest@69f080ad]" started-at="2023-08-03T14:45:13 ICT" name="testInsert" finished-at="2023-08-03T14:45:13 ICT" duration-ms="10" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.text.ParseException: Unparseable date: "01-05-2003"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.text.ParseException: Unparseable date: "01-05-2003"
at Khac.XDate.toDate(XDate.java:21)
at edusys.QLNH.getForm(QLNH.java:565)
at edusys.QLNH.insert(QLNH.java:485)
at testing.QLNHTest.testInsert(QLNHTest.java:45)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.text.ParseException: Unparseable date: "01-05-2003"
at java.base/java.text.DateFormat.parse(DateFormat.java:399)
at Khac.XDate.toDate(XDate.java:18)
... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInsert -->
        <test-method signature="testInsertTrungMNH()[pri:2, instance:testing.QLNHTest@69f080ad]" started-at="2023-08-03T14:45:13 ICT" name="testInsertTrungMNH" finished-at="2023-08-03T14:45:13 ICT" duration-ms="3" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.text.ParseException: Unparseable date: "01-05-2003"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.text.ParseException: Unparseable date: "01-05-2003"
at Khac.XDate.toDate(XDate.java:21)
at edusys.QLNH.getForm(QLNH.java:565)
at edusys.QLNH.insert(QLNH.java:485)
at testing.QLNHTest.testInsertTrungMNH(QLNHTest.java:56)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.text.ParseException: Unparseable date: "01-05-2003"
at java.base/java.text.DateFormat.parse(DateFormat.java:399)
at Khac.XDate.toDate(XDate.java:18)
... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInsertTrungMNH -->
        <test-method signature="testInsertNull()[pri:3, instance:testing.QLNHTest@69f080ad]" started-at="2023-08-03T14:45:13 ICT" name="testInsertNull" finished-at="2023-08-03T14:45:13 ICT" duration-ms="4" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.text.ParseException: Unparseable date: ""]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.text.ParseException: Unparseable date: ""
at Khac.XDate.toDate(XDate.java:21)
at edusys.QLNH.getForm(QLNH.java:565)
at edusys.QLNH.insert(QLNH.java:485)
at testing.QLNHTest.testInsertNull(QLNHTest.java:67)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.text.ParseException: Unparseable date: ""
at java.base/java.text.DateFormat.parse(DateFormat.java:399)
at Khac.XDate.toDate(XDate.java:18)
... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInsertNull -->
        <test-method signature="testUpdate()[pri:4, instance:testing.QLNHTest@69f080ad]" started-at="2023-08-03T14:45:13 ICT" name="testUpdate" finished-at="2023-08-03T14:45:13 ICT" duration-ms="3" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.text.ParseException: Unparseable date: "01-05-2000"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.text.ParseException: Unparseable date: "01-05-2000"
at Khac.XDate.toDate(XDate.java:21)
at edusys.QLNH.getForm(QLNH.java:565)
at edusys.QLNH.update(QLNH.java:498)
at testing.QLNHTest.testUpdate(QLNHTest.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.text.ParseException: Unparseable date: "01-05-2000"
at java.base/java.text.DateFormat.parse(DateFormat.java:399)
at Khac.XDate.toDate(XDate.java:18)
... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdate -->
        <test-method signature="testUpdateNull()[pri:5, instance:testing.QLNHTest@69f080ad]" started-at="2023-08-03T14:45:13 ICT" name="testUpdateNull" finished-at="2023-08-03T14:45:13 ICT" duration-ms="2" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.text.ParseException: Unparseable date: ""]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.text.ParseException: Unparseable date: ""
at Khac.XDate.toDate(XDate.java:21)
at edusys.QLNH.getForm(QLNH.java:565)
at edusys.QLNH.update(QLNH.java:498)
at testing.QLNHTest.testUpdateNull(QLNHTest.java:90)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.text.ParseException: Unparseable date: ""
at java.base/java.text.DateFormat.parse(DateFormat.java:399)
at Khac.XDate.toDate(XDate.java:18)
... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateNull -->
        <test-method signature="testDelete()[pri:6, instance:testing.QLNHTest@69f080ad]" started-at="2023-08-03T14:45:13 ICT" name="testDelete" finished-at="2023-08-03T14:45:14 ICT" duration-ms="974" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDelete -->
        <test-method signature="testDeleteLoi()[pri:7, instance:testing.QLNHTest@69f080ad]" started-at="2023-08-03T14:45:14 ICT" name="testDeleteLoi" finished-at="2023-08-03T14:45:15 ICT" duration-ms="666" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteLoi -->
        <test-method signature="testFindingKhongtontai()[pri:8, instance:testing.QLNHTest@69f080ad]" started-at="2023-08-03T14:45:15 ICT" name="testFindingKhongtontai" finished-at="2023-08-03T14:45:15 ICT" duration-ms="45" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFindingKhongtontai -->
        <test-method signature="testFindingNull()[pri:9, instance:testing.QLNHTest@69f080ad]" started-at="2023-08-03T14:45:15 ICT" name="testFindingNull" finished-at="2023-08-03T14:45:15 ICT" duration-ms="60" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFindingNull -->
        <test-method signature="testFinding()[pri:10, instance:testing.QLNHTest@69f080ad]" started-at="2023-08-03T14:45:15 ICT" name="testFinding" finished-at="2023-08-03T14:45:15 ICT" duration-ms="46" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFinding -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testing.QLNHTest@69f080ad]" started-at="2023-08-03T14:45:18 ICT" name="tearDown" finished-at="2023-08-03T14:45:18 ICT" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testing.QLNHTest -->
      <class name="testing.ChuyendeDAOTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testing.ChuyendeDAOTest@45d4421d]" started-at="2023-08-03T14:45:18 ICT" name="setUp" finished-at="2023-08-03T14:45:18 ICT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testInserHopLe(java.lang.String,java.lang.String,double,int,java.lang.String,java.lang.String)[pri:0, instance:testing.ChuyendeDAOTest@45d4421d]" started-at="2023-08-03T14:45:18 ICT" name="testInserHopLe" description="InsertValid" data-provider="validData" finished-at="2023-08-03T14:45:18 ICT" duration-ms="37" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[CD-001]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ChuyenDe1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[1000.0]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[30]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[image1.jpg]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[Mo ta cho chuyen de 1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[com.microsoft.sqlserver.jdbc.SQLServerException: String or binary data would be truncated in table 'ps25732_polypro.dbo.ChuyenDe', column 'MaCD'. Truncated value: 'CD-00'.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: String or binary data would be truncated in table 'ps25732_polypro.dbo.ChuyenDe', column 'MaCD'. Truncated value: 'CD-00'.
at Database.JDBC.update(JDBC.java:49)
at Database.ChuyendeDAO.insert(ChuyendeDAO.java:22)
at testing.ChuyendeDAOTest.testInserHopLe(ChuyendeDAOTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: String or binary data would be truncated in table 'ps25732_polypro.dbo.ChuyenDe', column 'MaCD'. Truncated value: 'CD-00'.
at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1673)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:620)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:540)
at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7627)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3912)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:486)
at Database.JDBC.update(JDBC.java:42)
... 28 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInserHopLe -->
        <test-method signature="testInserHopLe(java.lang.String,java.lang.String,double,int,java.lang.String,java.lang.String)[pri:0, instance:testing.ChuyendeDAOTest@45d4421d]" started-at="2023-08-03T14:45:18 ICT" name="testInserHopLe" description="InsertValid" data-provider="validData" finished-at="2023-08-03T14:45:18 ICT" duration-ms="28" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[CD-002]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ChuyenDe2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[1500.0]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[25]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[image2.jpg]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[Mo ta cho chuyen de 2]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[com.microsoft.sqlserver.jdbc.SQLServerException: String or binary data would be truncated in table 'ps25732_polypro.dbo.ChuyenDe', column 'MaCD'. Truncated value: 'CD-00'.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: String or binary data would be truncated in table 'ps25732_polypro.dbo.ChuyenDe', column 'MaCD'. Truncated value: 'CD-00'.
at Database.JDBC.update(JDBC.java:49)
at Database.ChuyendeDAO.insert(ChuyendeDAO.java:22)
at testing.ChuyendeDAOTest.testInserHopLe(ChuyendeDAOTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: String or binary data would be truncated in table 'ps25732_polypro.dbo.ChuyenDe', column 'MaCD'. Truncated value: 'CD-00'.
at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1673)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:620)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:540)
at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7627)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3912)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:486)
at Database.JDBC.update(JDBC.java:42)
... 28 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInserHopLe -->
        <test-method signature="testInserHopLe(java.lang.String,java.lang.String,double,int,java.lang.String,java.lang.String)[pri:0, instance:testing.ChuyendeDAOTest@45d4421d]" started-at="2023-08-03T14:45:18 ICT" name="testInserHopLe" description="InsertValid" data-provider="validData" finished-at="2023-08-03T14:45:18 ICT" duration-ms="24" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[CD-003]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ChuyenDe3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[800.0]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[20]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[image3.jpg]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[Mo ta cho chuyen de 3]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[com.microsoft.sqlserver.jdbc.SQLServerException: String or binary data would be truncated in table 'ps25732_polypro.dbo.ChuyenDe', column 'MaCD'. Truncated value: 'CD-00'.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: String or binary data would be truncated in table 'ps25732_polypro.dbo.ChuyenDe', column 'MaCD'. Truncated value: 'CD-00'.
at Database.JDBC.update(JDBC.java:49)
at Database.ChuyendeDAO.insert(ChuyendeDAO.java:22)
at testing.ChuyendeDAOTest.testInserHopLe(ChuyendeDAOTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: String or binary data would be truncated in table 'ps25732_polypro.dbo.ChuyenDe', column 'MaCD'. Truncated value: 'CD-00'.
at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1673)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:620)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:540)
at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7627)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3912)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:486)
at Database.JDBC.update(JDBC.java:42)
... 28 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInserHopLe -->
        <test-method signature="testInsertNULL(java.lang.String,java.lang.String,double,int,java.lang.String,java.lang.String)[pri:1, instance:testing.ChuyendeDAOTest@45d4421d]" started-at="2023-08-03T14:45:18 ICT" name="testInsertNULL" description="InsertNull" data-provider="nullData" finished-at="2023-08-03T14:45:18 ICT" duration-ms="22" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[0.0]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_ChuyenDe'. Cannot insert duplicate key in object 'dbo.ChuyenDe'. The duplicate key value is (     ).]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_ChuyenDe'. Cannot insert duplicate key in object 'dbo.ChuyenDe'. The duplicate key value is (     ).
at Database.JDBC.update(JDBC.java:49)
at Database.ChuyendeDAO.insert(ChuyendeDAO.java:22)
at testing.ChuyendeDAOTest.testInsertNULL(ChuyendeDAOTest.java:63)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_ChuyenDe'. Cannot insert duplicate key in object 'dbo.ChuyenDe'. The duplicate key value is (     ).
at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1673)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:620)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:540)
at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7627)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3912)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:486)
at Database.JDBC.update(JDBC.java:42)
... 28 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInsertNULL -->
        <test-method signature="testUpdateHopLe(java.lang.String,java.lang.String,double,int,java.lang.String,java.lang.String)[pri:2, instance:testing.ChuyendeDAOTest@45d4421d]" started-at="2023-08-03T14:45:18 ICT" name="testUpdateHopLe" description="UpdateValid" data-provider="validData" finished-at="2023-08-03T14:45:18 ICT" duration-ms="28" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[CD-001]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ChuyenDe1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[1000.0]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[30]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[image1.jpg]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[Mo ta cho chuyen de 1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateHopLe -->
        <test-method signature="testUpdateHopLe(java.lang.String,java.lang.String,double,int,java.lang.String,java.lang.String)[pri:2, instance:testing.ChuyendeDAOTest@45d4421d]" started-at="2023-08-03T14:45:18 ICT" name="testUpdateHopLe" description="UpdateValid" data-provider="validData" finished-at="2023-08-03T14:45:18 ICT" duration-ms="28" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[CD-002]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ChuyenDe2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[1500.0]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[25]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[image2.jpg]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[Mo ta cho chuyen de 2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateHopLe -->
        <test-method signature="testUpdateHopLe(java.lang.String,java.lang.String,double,int,java.lang.String,java.lang.String)[pri:2, instance:testing.ChuyendeDAOTest@45d4421d]" started-at="2023-08-03T14:45:18 ICT" name="testUpdateHopLe" description="UpdateValid" data-provider="validData" finished-at="2023-08-03T14:45:18 ICT" duration-ms="25" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[CD-003]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ChuyenDe3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[800.0]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[20]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[image3.jpg]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[Mo ta cho chuyen de 3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateHopLe -->
        <test-method signature="testUpdateNull(java.lang.String,java.lang.String,double,int,java.lang.String,java.lang.String)[pri:3, instance:testing.ChuyendeDAOTest@45d4421d]" started-at="2023-08-03T14:45:18 ICT" name="testUpdateNull" description="UpdateNull" data-provider="nullData" finished-at="2023-08-03T14:45:18 ICT" duration-ms="28" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[0.0]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateNull -->
        <test-method signature="testDeleteHopLe(java.lang.String)[pri:4, instance:testing.ChuyendeDAOTest@45d4421d]" started-at="2023-08-03T14:45:18 ICT" name="testDeleteHopLe" description="DeleteValid" data-provider="validData" finished-at="2023-08-03T14:45:18 ICT" duration-ms="2" status="FAIL">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void testing.ChuyendeDAOTest.testDeleteHopLe(java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testDeleteHopLe([java.lang.String arg0])
Arguments: [(java.lang.String) CD-001,(java.lang.String) ChuyenDe1,(java.lang.Double) 1000.0,(java.lang.Integer) 30,(java.lang.String) image1.jpg,(java.lang.String) Mo ta cho chuyen de 1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void testing.ChuyendeDAOTest.testDeleteHopLe(java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testDeleteHopLe([java.lang.String arg0])
Arguments: [(java.lang.String) CD-001,(java.lang.String) ChuyenDe1,(java.lang.Double) 1000.0,(java.lang.Integer) 30,(java.lang.String) image1.jpg,(java.lang.String) Mo ta cho chuyen de 1]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:909)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:37)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteHopLe -->
        <test-method signature="testDeleteNull(java.lang.String)[pri:5, instance:testing.ChuyendeDAOTest@45d4421d]" started-at="2023-08-03T14:45:18 ICT" name="testDeleteNull" description="DeleteNull" data-provider="nullData" finished-at="2023-08-03T14:45:18 ICT" duration-ms="0" status="FAIL">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void testing.ChuyendeDAOTest.testDeleteNull(java.lang.String) throws java.lang.Exception] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testDeleteNull([java.lang.String arg0])
Arguments: [(java.lang.String) ,(java.lang.String) ,(java.lang.Double) 0.0,(java.lang.Integer) 0,(java.lang.String) ,(java.lang.String) ]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void testing.ChuyendeDAOTest.testDeleteNull(java.lang.String) throws java.lang.Exception] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testDeleteNull([java.lang.String arg0])
Arguments: [(java.lang.String) ,(java.lang.String) ,(java.lang.Double) 0.0,(java.lang.Integer) 0,(java.lang.String) ,(java.lang.String) ]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:909)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:37)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteNull -->
        <test-method signature="testSelectAll()[pri:6, instance:testing.ChuyendeDAOTest@45d4421d]" started-at="2023-08-03T14:45:18 ICT" name="testSelectAll" description="SelectAll" finished-at="2023-08-03T14:45:18 ICT" duration-ms="45" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSelectAll -->
        <test-method signature="testSelectById()[pri:7, instance:testing.ChuyendeDAOTest@45d4421d]" started-at="2023-08-03T14:45:18 ICT" name="testSelectById" description="SelectById" finished-at="2023-08-03T14:45:18 ICT" duration-ms="49" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected object to not be null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.assertNotNull(Assert.java:1484)
at org.testng.Assert.assertNotNull(Assert.java:1468)
at testing.ChuyendeDAOTest.testSelectById(ChuyendeDAOTest.java:111)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSelectById -->
        <test-method signature="testSelectByIdNotFound()[pri:8, instance:testing.ChuyendeDAOTest@45d4421d]" started-at="2023-08-03T14:45:18 ICT" name="testSelectByIdNotFound" description="SelectByIdNotFound" finished-at="2023-08-03T14:45:18 ICT" duration-ms="24" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSelectByIdNotFound -->
      </class> <!-- testing.ChuyendeDAOTest -->
      <class name="testing.QLNVTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testing.QLNVTest@c97721b]" started-at="2023-08-03T14:45:02 ICT" name="setUp" finished-at="2023-08-03T14:45:02 ICT" duration-ms="173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testInsert()[pri:1, instance:testing.QLNVTest@c97721b]" started-at="2023-08-03T14:45:03 ICT" name="testInsert" finished-at="2023-08-03T14:45:04 ICT" duration-ms="1378" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInsert -->
        <test-method signature="testInsertTrungMNV()[pri:2, instance:testing.QLNVTest@c97721b]" started-at="2023-08-03T14:45:04 ICT" name="testInsertTrungMNV" finished-at="2023-08-03T14:45:05 ICT" duration-ms="589" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInsertTrungMNV -->
        <test-method signature="testInsertNULL()[pri:3, instance:testing.QLNVTest@c97721b]" started-at="2023-08-03T14:45:05 ICT" name="testInsertNULL" finished-at="2023-08-03T14:45:05 ICT" duration-ms="692" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInsertNULL -->
        <test-method signature="testUpdate()[pri:3, instance:testing.QLNVTest@c97721b]" started-at="2023-08-03T14:45:05 ICT" name="testUpdate" finished-at="2023-08-03T14:45:06 ICT" duration-ms="1056" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdate -->
        <test-method signature="testUpdateNULL()[pri:4, instance:testing.QLNVTest@c97721b]" started-at="2023-08-03T14:45:06 ICT" name="testUpdateNULL" finished-at="2023-08-03T14:45:07 ICT" duration-ms="719" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateNULL -->
        <test-method signature="testUpdateMNVKOTT()[pri:5, instance:testing.QLNVTest@c97721b]" started-at="2023-08-03T14:45:07 ICT" name="testUpdateMNVKOTT" finished-at="2023-08-03T14:45:08 ICT" duration-ms="691" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateMNVKOTT -->
        <test-method signature="testDelete()[pri:6, instance:testing.QLNVTest@c97721b]" started-at="2023-08-03T14:45:08 ICT" name="testDelete" finished-at="2023-08-03T14:45:09 ICT" duration-ms="1213" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDelete -->
        <test-method signature="testDeleteNull()[pri:7, instance:testing.QLNVTest@c97721b]" started-at="2023-08-03T14:45:09 ICT" name="testDeleteNull" finished-at="2023-08-03T14:45:10 ICT" duration-ms="669" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteNull -->
        <test-method signature="testDeleteMNVKOTT()[pri:8, instance:testing.QLNVTest@c97721b]" started-at="2023-08-03T14:45:10 ICT" name="testDeleteMNVKOTT" finished-at="2023-08-03T14:45:10 ICT" duration-ms="620" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteMNVKOTT -->
        <test-method signature="testDeleteLogin()[pri:9, instance:testing.QLNVTest@c97721b]" started-at="2023-08-03T14:45:10 ICT" name="testDeleteLogin" finished-at="2023-08-03T14:45:11 ICT" duration-ms="930" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testing.QLNVTest@c97721b]" started-at="2023-08-03T14:45:11 ICT" name="tearDown" finished-at="2023-08-03T14:45:11 ICT" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testing.QLNVTest -->
      <class name="testing.DoiMKTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testing.DoiMKTest@6568f998]" started-at="2023-08-03T14:45:15 ICT" name="setUp" finished-at="2023-08-03T14:45:15 ICT" duration-ms="52" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testDoiMatKhauSaiMK()[pri:1, instance:testing.DoiMKTest@6568f998]" started-at="2023-08-03T14:45:15 ICT" name="testDoiMatKhauSaiMK" finished-at="2023-08-03T14:45:16 ICT" duration-ms="1393" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDoiMatKhauSaiMK -->
        <test-method signature="testDoiMatKhauKhongKhop()[pri:2, instance:testing.DoiMKTest@6568f998]" started-at="2023-08-03T14:45:16 ICT" name="testDoiMatKhauKhongKhop" finished-at="2023-08-03T14:45:17 ICT" duration-ms="691" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDoiMatKhauKhongKhop -->
        <test-method signature="testDoiMatKhauHopLe()[pri:3, instance:testing.DoiMKTest@6568f998]" started-at="2023-08-03T14:45:17 ICT" name="testDoiMatKhauHopLe" finished-at="2023-08-03T14:45:18 ICT" duration-ms="597" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDoiMatKhauHopLe -->
        <test-method is-config="true" signature="Teardown()[pri:0, instance:testing.DoiMKTest@6568f998]" started-at="2023-08-03T14:45:18 ICT" name="Teardown" finished-at="2023-08-03T14:45:18 ICT" duration-ms="13" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Teardown -->
      </class> <!-- testing.DoiMKTest -->
      <class name="testing.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testing.LoginTest@718989fa]" started-at="2023-08-03T14:45:11 ICT" name="setUp" finished-at="2023-08-03T14:45:11 ICT" duration-ms="24" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testDangNhapNULL()[pri:1, instance:testing.LoginTest@718989fa]" started-at="2023-08-03T14:45:11 ICT" name="testDangNhapNULL" finished-at="2023-08-03T14:45:11 ICT" duration-ms="66" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDangNhapNULL -->
        <test-method signature="testDangNhapSai()[pri:2, instance:testing.LoginTest@718989fa]" started-at="2023-08-03T14:45:11 ICT" name="testDangNhapSai" finished-at="2023-08-03T14:45:13 ICT" duration-ms="1667" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "Models.Nhanvien.getMatKhau()" because "nv" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "Models.Nhanvien.getMatKhau()" because "nv" is null
at edusys.Login.dangNhap(Login.java:210)
at testing.LoginTest.testDangNhapSai(LoginTest.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDangNhapSai -->
        <test-method signature="testDangNhapHopLe()[pri:3, instance:testing.LoginTest@718989fa]" started-at="2023-08-03T14:45:13 ICT" name="testDangNhapHopLe" finished-at="2023-08-03T14:45:13 ICT" duration-ms="63" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDangNhapHopLe -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testing.LoginTest@718989fa]" started-at="2023-08-03T14:45:13 ICT" name="tearDown" finished-at="2023-08-03T14:45:13 ICT" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testing.LoginTest -->
      <class name="edusys.LoginTest">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:00 ICT" name="beforeSuite" finished-at="2023-08-03T14:45:00 ICT" duration-ms="30" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:00 ICT" name="beforeTest" finished-at="2023-08-03T14:45:00 ICT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="LoginTest()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="LoginTest" finished-at="2023-08-03T14:45:18 ICT" duration-ms="1" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Test not implemented]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Test not implemented
at edusys.LoginTest.LoginTest(LoginTest.java:44)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="beforeClass" finished-at="2023-08-03T14:45:18 ICT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="afterMethod" finished-at="2023-08-03T14:45:18 ICT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="btnDangNhapActionPerformedTest()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="btnDangNhapActionPerformedTest" finished-at="2023-08-03T14:45:18 ICT" duration-ms="1" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Test not implemented]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Test not implemented
at edusys.LoginTest.btnDangNhapActionPerformedTest(LoginTest.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- btnDangNhapActionPerformedTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="afterMethod" finished-at="2023-08-03T14:45:18 ICT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="btnDangNhapKeyPressedTest()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="btnDangNhapKeyPressedTest" finished-at="2023-08-03T14:45:18 ICT" duration-ms="1" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Test not implemented]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Test not implemented
at edusys.LoginTest.btnDangNhapKeyPressedTest(LoginTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- btnDangNhapKeyPressedTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="afterMethod" finished-at="2023-08-03T14:45:18 ICT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="btnExitActionPerformedTest()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="btnExitActionPerformedTest" finished-at="2023-08-03T14:45:18 ICT" duration-ms="2" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Test not implemented]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Test not implemented
at edusys.LoginTest.btnExitActionPerformedTest(LoginTest.java:59)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- btnExitActionPerformedTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="afterMethod" finished-at="2023-08-03T14:45:18 ICT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="dangNhapTest()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="dangNhapTest" finished-at="2023-08-03T14:45:18 ICT" duration-ms="1" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Test not implemented]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Test not implemented
at edusys.LoginTest.dangNhapTest(LoginTest.java:64)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dangNhapTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="afterMethod" finished-at="2023-08-03T14:45:18 ICT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="initComponentsTest()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="initComponentsTest" finished-at="2023-08-03T14:45:18 ICT" duration-ms="1" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Test not implemented]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Test not implemented
at edusys.LoginTest.initComponentsTest(LoginTest.java:69)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initComponentsTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="afterMethod" finished-at="2023-08-03T14:45:18 ICT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="jLabel5MouseClickedTest()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="jLabel5MouseClickedTest" finished-at="2023-08-03T14:45:18 ICT" duration-ms="1" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Test not implemented]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Test not implemented
at edusys.LoginTest.jLabel5MouseClickedTest(LoginTest.java:74)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- jLabel5MouseClickedTest -->
        <test-method signature="ketThucTest()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="ketThucTest" finished-at="2023-08-03T14:45:18 ICT" duration-ms="1" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Test not implemented]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Test not implemented
at edusys.LoginTest.ketThucTest(LoginTest.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ketThucTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="afterMethod" finished-at="2023-08-03T14:45:18 ICT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="afterMethod" finished-at="2023-08-03T14:45:18 ICT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="mainTest()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="mainTest" finished-at="2023-08-03T14:45:18 ICT" duration-ms="1" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Test not implemented]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Test not implemented
at edusys.LoginTest.mainTest(LoginTest.java:84)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mainTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="afterMethod" finished-at="2023-08-03T14:45:18 ICT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="txtMaNVActionPerformedTest()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="txtMaNVActionPerformedTest" finished-at="2023-08-03T14:45:18 ICT" duration-ms="1" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Test not implemented]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Test not implemented
at edusys.LoginTest.txtMaNVActionPerformedTest(LoginTest.java:89)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- txtMaNVActionPerformedTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="afterMethod" finished-at="2023-08-03T14:45:18 ICT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="afterClass" finished-at="2023-08-03T14:45:18 ICT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:18 ICT" name="afterTest" finished-at="2023-08-03T14:45:18 ICT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:edusys.LoginTest@7db5b890]" started-at="2023-08-03T14:45:19 ICT" name="afterSuite" finished-at="2023-08-03T14:45:19 ICT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- edusys.LoginTest -->
      <class name="testing.NguoihocDAOTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testing.NguoihocDAOTest@7a358613]" started-at="2023-08-03T14:45:18 ICT" name="setUp" finished-at="2023-08-03T14:45:18 ICT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testInsertHopLe(java.lang.String,java.lang.String,java.lang.String,boolean,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testing.NguoihocDAOTest@7a358613]" started-at="2023-08-03T14:45:18 ICT" name="testInsertHopLe" description="InsertValid" data-provider="validData" finished-at="2023-08-03T14:45:18 ICT" duration-ms="42" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[nh-01]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[UyenPhuong]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[09/08/2002]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[0328645096]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[uynphng765@gmail.com]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[hehe]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[TeoNV]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[08/07/2023]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_NguoiHoc'. Cannot insert duplicate key in object 'dbo.NguoiHoc'. The duplicate key value is (nh-01  ).]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_NguoiHoc'. Cannot insert duplicate key in object 'dbo.NguoiHoc'. The duplicate key value is (nh-01  ).
at Database.JDBC.update(JDBC.java:49)
at Database.NguoihocDAO.insert(NguoihocDAO.java:22)
at testing.NguoihocDAOTest.testInsertHopLe(NguoihocDAOTest.java:58)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_NguoiHoc'. Cannot insert duplicate key in object 'dbo.NguoiHoc'. The duplicate key value is (nh-01  ).
at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1673)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:620)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:540)
at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7627)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3912)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:486)
at Database.JDBC.update(JDBC.java:42)
... 28 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInsertHopLe -->
        <test-method signature="testInsertHopLe(java.lang.String,java.lang.String,java.lang.String,boolean,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testing.NguoihocDAOTest@7a358613]" started-at="2023-08-03T14:45:18 ICT" name="testInsertHopLe" description="InsertValid" data-provider="validData" finished-at="2023-08-03T14:45:18 ICT" duration-ms="34" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[nh-02]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[UyenPhuong]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[09/08/2002]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[0328645096]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[uynphng765@gmail.com]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[hehe]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[uyenphuong]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[08/07/2023]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[com.microsoft.sqlserver.jdbc.SQLServerException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_NguoiHoc_NhanVien". The conflict occurred in database "ps25732_polypro", table "dbo.NhanVien", column 'MaNV'.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_NguoiHoc_NhanVien". The conflict occurred in database "ps25732_polypro", table "dbo.NhanVien", column 'MaNV'.
at Database.JDBC.update(JDBC.java:49)
at Database.NguoihocDAO.insert(NguoihocDAO.java:22)
at testing.NguoihocDAOTest.testInsertHopLe(NguoihocDAOTest.java:58)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_NguoiHoc_NhanVien". The conflict occurred in database "ps25732_polypro", table "dbo.NhanVien", column 'MaNV'.
at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1673)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:620)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:540)
at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7627)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3912)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:486)
at Database.JDBC.update(JDBC.java:42)
... 28 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInsertHopLe -->
        <test-method signature="testInsertNULL(java.lang.String,java.lang.String,java.lang.String,boolean,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:testing.NguoihocDAOTest@7a358613]" started-at="2023-08-03T14:45:18 ICT" name="testInsertNULL" description="InsertNull" data-provider="nullData" finished-at="2023-08-03T14:45:18 ICT" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.text.ParseException">
            <message>
              <![CDATA[Unparseable date: ""]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.text.ParseException: Unparseable date: ""
at java.base/java.text.DateFormat.parse(DateFormat.java:399)
at testing.NguoihocDAOTest.testInsertNULL(NguoihocDAOTest.java:67)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.text.ParseException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInsertNULL -->
        <test-method signature="testUpdateHopLe(java.lang.String,java.lang.String,java.lang.String,boolean,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:2, instance:testing.NguoihocDAOTest@7a358613]" started-at="2023-08-03T14:45:18 ICT" name="testUpdateHopLe" description="UpdateValid" data-provider="validData" finished-at="2023-08-03T14:45:18 ICT" duration-ms="26" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[nh-01]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[UyenPhuong]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[09/08/2002]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[0328645096]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[uynphng765@gmail.com]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[hehe]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[TeoNV]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[08/07/2023]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateHopLe -->
        <test-method signature="testUpdateHopLe(java.lang.String,java.lang.String,java.lang.String,boolean,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:2, instance:testing.NguoihocDAOTest@7a358613]" started-at="2023-08-03T14:45:18 ICT" name="testUpdateHopLe" description="UpdateValid" data-provider="validData" finished-at="2023-08-03T14:45:18 ICT" duration-ms="23" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[nh-02]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[UyenPhuong]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[09/08/2002]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[0328645096]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[uynphng765@gmail.com]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[hehe]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[uyenphuong]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[08/07/2023]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateHopLe -->
        <test-method signature="testUpdateNULL(java.lang.String,java.lang.String,java.lang.String,boolean,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:3, instance:testing.NguoihocDAOTest@7a358613]" started-at="2023-08-03T14:45:18 ICT" name="testUpdateNULL" description="UpdateNull" data-provider="nullData" finished-at="2023-08-03T14:45:18 ICT" duration-ms="1" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.text.ParseException">
            <message>
              <![CDATA[Unparseable date: ""]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.text.ParseException: Unparseable date: ""
at java.base/java.text.DateFormat.parse(DateFormat.java:399)
at testing.NguoihocDAOTest.testUpdateNULL(NguoihocDAOTest.java:99)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.text.ParseException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateNULL -->
        <test-method signature="testDeleteHopLe(java.lang.String)[pri:4, instance:testing.NguoihocDAOTest@7a358613]" started-at="2023-08-03T14:45:18 ICT" name="testDeleteHopLe" description="DeleteValid" data-provider="validData" finished-at="2023-08-03T14:45:18 ICT" duration-ms="0" status="FAIL">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void testing.NguoihocDAOTest.testDeleteHopLe(java.lang.String) throws java.text.ParseException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testDeleteHopLe([java.lang.String arg0])
Arguments: [(java.lang.String) nh-01,(java.lang.String) UyenPhuong,(java.lang.String) 09/08/2002,(java.lang.Boolean) true,(java.lang.String) 0328645096,(java.lang.String) uynphng765@gmail.com,(java.lang.String) hehe,(java.lang.String) TeoNV,(java.lang.String) 08/07/2023]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void testing.NguoihocDAOTest.testDeleteHopLe(java.lang.String) throws java.text.ParseException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testDeleteHopLe([java.lang.String arg0])
Arguments: [(java.lang.String) nh-01,(java.lang.String) UyenPhuong,(java.lang.String) 09/08/2002,(java.lang.Boolean) true,(java.lang.String) 0328645096,(java.lang.String) uynphng765@gmail.com,(java.lang.String) hehe,(java.lang.String) TeoNV,(java.lang.String) 08/07/2023]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:909)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:37)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteHopLe -->
        <test-method signature="testDeleteNULL(java.lang.String)[pri:5, instance:testing.NguoihocDAOTest@7a358613]" started-at="2023-08-03T14:45:18 ICT" name="testDeleteNULL" description="DeleteNull" data-provider="nullData" finished-at="2023-08-03T14:45:18 ICT" duration-ms="0" status="FAIL">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void testing.NguoihocDAOTest.testDeleteNULL(java.lang.String) throws java.lang.Exception] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testDeleteNULL([java.lang.String arg0])
Arguments: [(java.lang.String) ,(java.lang.String) ,(java.lang.String) ,(java.lang.Boolean) false,(java.lang.String) ,(java.lang.String) ,(java.lang.String) ,(java.lang.String) ,(java.lang.String) ]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void testing.NguoihocDAOTest.testDeleteNULL(java.lang.String) throws java.lang.Exception] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testDeleteNULL([java.lang.String arg0])
Arguments: [(java.lang.String) ,(java.lang.String) ,(java.lang.String) ,(java.lang.Boolean) false,(java.lang.String) ,(java.lang.String) ,(java.lang.String) ,(java.lang.String) ,(java.lang.String) ]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:909)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:37)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteNULL -->
      </class> <!-- testing.NguoihocDAOTest -->
      <class name="testing.NhanVienDAOTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testing.NhanVienDAOTest@760f1081]" started-at="2023-08-03T14:45:18 ICT" name="setUp" finished-at="2023-08-03T14:45:18 ICT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testInsertHopLe()[pri:0, instance:testing.NhanVienDAOTest@760f1081]" started-at="2023-08-03T14:45:18 ICT" name="testInsertHopLe" description="InsertValid" finished-at="2023-08-03T14:45:18 ICT" duration-ms="28" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInsertHopLe -->
        <test-method signature="testInsertNull()[pri:1, instance:testing.NhanVienDAOTest@760f1081]" started-at="2023-08-03T14:45:18 ICT" name="testInsertNull" description="InsertNull" finished-at="2023-08-03T14:45:18 ICT" duration-ms="19" status="PASS">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_QuanTri'. Cannot insert duplicate key in object 'dbo.NhanVien'. The duplicate key value is ().]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_QuanTri'. Cannot insert duplicate key in object 'dbo.NhanVien'. The duplicate key value is ().
at Database.JDBC.update(JDBC.java:49)
at Database.NhanviienDAO.insert(NhanviienDAO.java:21)
at testing.NhanVienDAOTest.testInsertNull(NhanVienDAOTest.java:46)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_QuanTri'. Cannot insert duplicate key in object 'dbo.NhanVien'. The duplicate key value is ().
at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1673)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:620)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:540)
at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7627)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3912)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:486)
at Database.JDBC.update(JDBC.java:42)
... 28 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInsertNull -->
        <test-method signature="testUpdateHopLe()[pri:2, instance:testing.NhanVienDAOTest@760f1081]" started-at="2023-08-03T14:45:18 ICT" name="testUpdateHopLe" description="UpdateValid" finished-at="2023-08-03T14:45:18 ICT" duration-ms="21" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateHopLe -->
        <test-method signature="testUpdateNull()[pri:3, instance:testing.NhanVienDAOTest@760f1081]" started-at="2023-08-03T14:45:18 ICT" name="testUpdateNull" description="UpdateNull" finished-at="2023-08-03T14:45:18 ICT" duration-ms="20" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateNull -->
        <test-method signature="testDeleteHopLe()[pri:4, instance:testing.NhanVienDAOTest@760f1081]" started-at="2023-08-03T14:45:18 ICT" name="testDeleteHopLe" description="DeleteValid" finished-at="2023-08-03T14:45:18 ICT" duration-ms="31" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteHopLe -->
        <test-method signature="testDeleteNull()[pri:5, instance:testing.NhanVienDAOTest@760f1081]" started-at="2023-08-03T14:45:18 ICT" name="testDeleteNull" description="DeleteNull" finished-at="2023-08-03T14:45:18 ICT" duration-ms="33" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteNull -->
      </class> <!-- testing.NhanVienDAOTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
